-- DROP SCHEMA, TABLE AND SEQUENCES
DROP TABLE IF EXISTS BOOKS;
DROP SEQUENCE IF EXISTS BOOK_SEQ;

DROP TABLE IF EXISTS GENRE;
DROP SEQUENCE IF EXISTS GENRE_SEQ;

DROP TABLE IF EXISTS AUTHOR;
DROP SEQUENCE IF EXISTS AUTHOR_SEQ;

DROP TABLE IF EXISTS PUBLISHER;
DROP SEQUENCE IF EXISTS PUBLISHER_SEQ;

DROP TABLE IF EXISTS ENTITY_VIEW;
DROP SEQUENCE IF EXISTS ENTITY_VIEW_SEQ;

DROP TABLE IF EXISTS ENTITY;
DROP SEQUENCE IF EXISTS ENTITY_SEQ;

-- GENRE SCHEMA
CREATE SEQUENCE GENRE_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE TABLE GENRE(
ID BIGINT DEFAULT nextval('GENRE_SEQ') PRIMARY KEY,
NAME VARCHAR(255));

-- AUTHOR SCHEMA
CREATE SEQUENCE AUTHOR_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE TABLE AUTHOR(
AUTHOR_ID BIGINT DEFAULT nextval('AUTHOR_SEQ') PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
NATIONALITY VARCHAR(200) NOT NULL);

-- PUBLISHER SCHEMA
CREATE SEQUENCE PUBLISHER_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE TABLE PUBLISHER(
PUBLISHER_ID BIGINT DEFAULT nextval('PUBLISHER_SEQ') PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
COUNTRY VARCHAR(255) NOT NULL);

-- BOOK SCHEMA
CREATE SEQUENCE BOOK_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE TABLE BOOKS(
ID BIGINT DEFAULT nextval('BOOK_SEQ') PRIMARY KEY,
NAME VARCHAR(255),
AUTHOR_ID BIGINT,
GENRE_ID BIGINT,
PUBLISHED_DATE DATE,
PUBLISHER_ID BIGINT,
LANGUAGE VARCHAR(250),
COST INT NOT NULL,
CURRENCY VARCHAR(10) NOT NULL,
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID),
FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID),
FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER(PUBLISHER_ID));

-- ENTITY SCHEMA
CREATE SEQUENCE ENTITY_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE TABLE ENTITY(
ENTITY_ID BIGINT DEFAULT nextval('ENTITY_SEQ') PRIMARY KEY,
NAME VARCHAR(255));

-- ENTITY_VIEW SCHEMA
CREATE SEQUENCE ENTITY_VIEW_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE TABLE ENTITY_VIEW(
ENTITY_VIEW_ID BIGINT DEFAULT nextval('ENTITY_VIEW_SEQ') PRIMARY KEY,
ENTITY_ID BIGINT,
ATTRIBUTE VARCHAR(25),
ATTrIBUTE_LABEL VARCHAR(25),
INPUT_TYPE VARCHAR(25),
IS_ENTITY BOOLEAN,
COMPOSED_ENTITY VARCHAR(25),
FOREIGN KEY (ENTITY_ID) REFERENCES ENTITY(ENTITY_ID));
