management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health, routes
eureka:
  client:
    healthcheck:
      enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500