-- DROP SEQUENCE AND TABLES
DROP TABLE IF EXISTS VEGETABLE;
DROP SEQUENCE IF EXISTS VEGETABLE_SEQ;

-- CREATE SEQUENCE AND TABLES
CREATE SEQUENCE VEGETABLE_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE VEGETABLE(
VEGETABLE_ID BIGINT DEFAULT VEGETABLE_SEQ.nextval PRIMARY KEY,
NAME VARCHAR(100) NOT NULL);
