server:
  port: 8082

spring:
  profiles:
    active: default
  datasource:
    url: jdbc:h2:file:~/report-test
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      path: /h2-report-test
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    
