TRUNCATE TABLE USER;
INSERT INTO USER (NAME, DESIGNATION) VALUES ('Chaitanya Ankam', 'Asoc');
INSERT INTO USER (NAME, DESIGNATION) VALUES ('Komali Bhadram', 'Asoc');
INSERT INTO USER (NAME, DESIGNATION) VALUES ('Sanjay Pareek', 'Asoc');