DROP TABLE IF EXISTS USER;
DROP SEQUENCE IF EXISTS USER_SEQ;

CREATE SEQUENCE USER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE USER(
ID BIGINT DEFAULT USER_SEQ.nextval PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
DESIGNATION VARCHAR(100) NOT NULL);