server:
  port: ${SERVER_PORT}
spring:
  profiles:
    active: ${ACTIVE_PROFILES}
  cloud:
    config:
      discovery:
        enabled: false
      server:
        encrypt.enabled: false
        git:
          uri: ${GIT_CONFIGURATION_URI}
          searchPaths: farmlandmgmt,farmvegetablemgmt
          username: ${GIT_USERNAME}
          password: ${GIT_PWD}